[package]
name = "eisen-bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "eisen_bridge"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
eisen-core = { path = "../core" }
serde_json = "1"
indextree = "4.6"
