[package]
name = "eisen-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
eisen-core = { path = "../../core" }
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"
serde_json = "1"
indextree = "4.6"

[build-dependencies]
napi-build = "2"
